apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  POSTGRES_HOST: "pg-svc" # <- name of the service that exposes the Postgres pod
  POSTGRES_DB: "ortkcbqt"
  PGDATA: "/var/lib/postgresql/data/1"

  RAILS_ENV: "production"
  NODE_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "false"
  BUNDLE_PATH: "vendor/bundle"
  BUNDLER_VERSION: "2.2.26" #<-------- SUPER IMPORTANT  !!!!!
  RUBY_VERSION: "3.0.2-alpine"

  REDIS_DB: "redis://redis-svc:6379/0"
  REDIS_SIDEKIQ: "redis://redis-svc:6379/1"
  REDIS_CACHE: "redis://redis-svc:6379/2"
  REDIS_CABLE: "redis://redis-svc:6379/3"
  #CABLE_ORIGIN: "ws://localhost:3000"
  # POSTGRES_URL: postgresql://postgres:dockerpassword@pg:5432/ortkcbqt
  # POSTGRES_URL: postgres://ortkcbqt:fhSBQrF3Dzl9WWA1FfRIjQmU7u3pBtTd@batyr.db.elephantsql.com/ortkcbqt
  # REDIS_SIDEKIQ: redis://user:tq4hBlYvIvq0uU7hYMOYS6ErQKsSA2N8@redis-13424.c258.us-east-1-4.ec2.cloud.redislabs.com:13424
