apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-serv-dep
  labels: # must match the service
    app: k8serv
spec:
  replicas: 1
  selector:
    matchLabels: # which pods are we deploying
      app: k8serv
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels: # must match service and replicaset matchlabel
        app: k8serv
    spec:
      # serviceAccountName: rails #<--- test access k8 cli in pod
      containers:
        - name: server-k8
          image: ndrean/serverk8-proxy
          command: ["kubectl", "proxy"]

          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 8001
          #     scheme: HTTP
          #     initialDelaySeconds: 60
          #     periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: k8-serv-svc
  labels:
    app: k8serv
spec:
  selector:
    app: k8serv
  type: NodePort # default type
  ports:
    - protocol: TCP
      # port exposed by the service
      port: 8002
      # the port the app is listening on targetPort
      targetPort: 8002
      name: http
