apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-ngx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: rails-ngx
    spec:
      containers:
        - image: ndrean/podserv:v0
          imagePullPolicy: Always
          name: webserver
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
---
apiVersion: v1
kind: Service
metadata:
  name: rails-ngx-svc
spec:
  type: NodePort
  selector:
    app: rails-ngx
  ports:
    - port: 80
      targetPort: 8080
