# create/provision/allocate space for a volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
  labels:
    #   type: local
    app: pg
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath: # for dvpt on single-node such as Minikube, to emulate network attached vol
    path: "/tmp/data"
