apiVersion: v1
kind: Service
metadata:
  name: pg-svc
  labels:
    app: pg #### pg # <- must match with the pod
spec:
  ports:
    - protocol: TCP
      port: 5432 # <- service port opened for Rails
  selector:
    # the set of pods with name 'pg' is targeted by this service
    app: pg

---
# Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  # about the deployment itself. Gives a name of the DEPLOYMENT
  name: pg-dep
  labels:
    app: pg
spec: # of the deployment
  serviceName: pg-dep
  replicas: 1
  selector:
    # the deployment must match all pods with label "app: pg"
    matchLabels:
      # the label for the POD that the deployment is targeting
      app: pg # <- must match with the template for the pod, below
  template: # blue print of a pod
    metadata:
      name: pg-pod
      # label for the POD that the deployment is deploying
      labels:
        app: pg # <- must match SERVICE
    spec:
      volumes:
        - name: pg-pv # must match pv
          persistentVolumeClaim:
            claimName: pg-pvc # msut match pvc
      containers:
        - name: pg-container
          image: postgres:13.3-alpine
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: "150Mi"
              cpu: "16m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pg-pv # must match pv
              readOnly: false
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
          # env:
          # - name: POSTGRES_PASSWORD
          #   # value: "dockerpassword"
          #   valueFrom:
          #     secretKeyRef:
          #       name: secrets
          #       key: postgres_password
          # - name: POSTGRES_USER
          #   # value: "postgres"
          #   valueFrom:
          #     secretKeyRef:
          #       name: secrets
          #       key: postgres_user
          # - name: DATABASE
          #   value: "ortkcbqt"
          # - name: PGDATA
          #   value: /var/lib/postgresql/data

---
# we bind the resource PV to the pod
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  #### volumeName: pg-pv
