apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
  # labels:
  #   app: k8-rails
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails
          image: ndrean/app:v5
          command: ["bundle"]
          args: ["exec", "rails", "s", "-b", "0.0.0.0"]
          ports:
            - containerPort: 3000
          # envFrom:
          #   - configMapRef:
          #       name: env
          env:
            - name: ELEPHANT_URL
              value: "postgres://ortkcbqt:fhSBQrF3Dzl9WWA1FfRIjQmU7u3pBtTd@batyr.db.elephantsql.com/ortkcbqt"
            - name: RAILS_ENV
              value: "production"
            - name: NODE_ENV
              value: "production"
            - name: REDIS_URL
              value: redis://user:tq4hBlYvIvq0uU7hYMOYS6ErQKsSA2N8@redis-13424.c258.us-east-1-4.ec2.cloud.redislabs.com:13424

---
apiVersion: v1
kind: Service
metadata:
  name: rails-svc
spec:
  type: NodePort
  selector:
    app: rails
  ports:
    - protocol: TCP
      # port exposed by the container
      port: 4000
      # the port the app is listening on targetPort
      targetPort: 3000
      name: http
