apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-dep
  labels:
    app: rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: backend
          image: ndrean/rails-pg-local:v1
          imagePullPolicy: "Always"
          command: ["bundle"]
          args: ["exec", "rails", "server", "-b", "0.0.0.0"]
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: POSTGRES_PASSWORD
              value: "dockerpassword"
              # valueFrom:
              #   secretKeyRef:
              #     name: secrets
              #     key: postgres_password
            - name: POSTGRES_USER
              value: "postgres"
              # valueFrom:
              #   secretKeyRef:
              #     name: secrets
              #     key: postgres_user
            - name: POSTGRES_HOST
              value: "pg"
              # valueFrom:
              #   configMapKeyRef:
              #     name: config
              #     key: postgres_host
            - name: DATABASE
              value: "ortkcbqt"
              # valueFrom:
              #   configMapKeyRef:
              #     name: config
              #     key: database
            - name: POSTGRES_HOST
              value: "pg-svc"
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: rails_master_key
            - name: REDIS_SIDEKIQ
              value: "redis-svc"
            - name: REDIS_PORT
              value: "6379"
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: rails_env
            - name: RAILS_LOGS_TO_STDOUT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: rails_log_to_stdout
            - name: RAILS_SERVE_STATIC_FILES
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: rails_serve_static_files

---
apiVersion: v1
kind: Service
metadata:
  name: rails-svc
  labels:
    app: rails
spec:
  selector:
    app: rails
  type: ClusterIP # default type
  ports:
    - protocol: TCP
      # port exposed by the service
      port: 3000
      # the port the app is listening on targetPort
      targetPort: 3000
      name: http
