apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    #   type: local
    app: data
spec:
  storageClassName: hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath: # for dvpt on single-node such as Minikube, to emulate network attached vol
    path: "/data"
