apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: app
spec:
  ports:
    - port: 6379
  selector:
    app: app
    tier: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: app
    tier: redis
  template:
    metadata:
      name: redis
      labels:
        app: app
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.4-alpine
          ports:
            - containerPort: 6379
