apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    app: data
  annotations:
    tilt.dev/down-policy: keep
spec:
  # storageClassName: "standard"
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteOnce
  hostPath: # for dvpt on single-node such as Minikube, to emulate network attached vol
    path: "/data"
