apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: client
  selector:
    app: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-dep
  labels:
    app: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.4-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          volumeMounts:
            # - name: conf
            #   mountPath: /conf
            #   readOnly: false
            - name: data
              mountPath: "/data"
              readOnly: false
      # volumes:
      #   - conf: conf
      #     configMap:
      #       name: redis
      #       defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteMany"]
        # storageClassName: "hostpath"
        resources:
          requests:
            storage: 50Mi
