apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: sidekiq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        # app: rails
        instance: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: ndrean/rails-pg-local:v1
          imagePullPolicy: "Always"
          command: ["bundle"]
          args: ["exec", "sidekiq", "-C", "./config/sidekiq.yml"]
          envFrom:
            - configMapRef:
                name: config
          env:
            - name: REDIS_SIDEKIQ
              #value: "redis://redis-svc:6379/0"
              # value: "redis://redis.default.svc.cluster.local:6379/"
              value: "redis://user:tq4hBlYvIvq0uU7hYMOYS6ErQKsSA2N8@redis-13424.c258.us-east-1-4.ec2.cloud.redislabs.com:13424/0"
              #value: redis://redis.default.svc.cluster.local:6379/
              # - name: REDIS_SIDEKIQ
          ports:
            - name: sidekiqalive
              containerPort: 7433
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30 # app specific. Time your sidekiq takes to start processing.

