apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: sidekiq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        # app: rails
        instance: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: ndrean/rails-base
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "150m"
              memory: "256Mi"
          command: ["bundle"]
          args:
            [
              "exec",
              "sidekiq",
              "-C",
              "./config/sidekiq.yml",
              "DISABLE_SIDEKIQ_ALIVE=true",
            ]
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
          ports:
            - name: sidekiqalive
              containerPort: 7433
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30 # app specific. Time your sidekiq takes to start processing.

