apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: sidekiq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        # app: rails
        instance: sidekiq
    spec:
      serviceAccountName: sidekiq
      containers:
        - name: server-k8
          image: ndrean/serverk8-proxy
          command: ["kubectl", "proxy"]
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
        - name: sidekiq
          image: ndrean/rails-base
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "250m"
              memory: "150Mi"
          command: ["bundle"]
          args: ["exec", "sidekiq", "-C", "./config/sidekiq.yml"]
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
