apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  # POSTGRES_USER: cG9zdGdyZXM= # postgres
  # POSTGRES_PASSWORD: ZG9ja2VycGFzc3dvcmQ= # dockerpassword
  POSTGRES_PASSWORD: ZmhTQlFyRjNEemw5V1dBMUZmUklqUW1VN3UzcEJ0VGQ= # elephantSQL pwd
  RAILS_MASTER_KEY: NWE0YmU0MzVjNmViODdhMWE5NTA3M2Y0YTRjYWNjYTg= # 5a4be435c6eb87a1a95073f4a4cacca8
