version: "3"

# see https://stackoverflow.com/questions/45805380/meaning-of-ampersand-in-docker-compose-yml-file
x-app: &common
  env_file: .env
  build:
    context: .
    dockerfile: _alpine.Dockerfile
    args:
      - RUBY_VERSION=3.0.1-alpine
      - BUNDLER_VERSION=2.2.21
      - NODE_VERSION=14
      - NODE_ENV=production
      - RAILS_ENV=production
      - USER_ID=${USER_ID:-501}
      - GROUP_ID=${GROUP_ID:-20}

services:
  pg:
    image: postgres:13.3-alpine
    ports:
      - 5432
    # <- the env file contains the URL with the password
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      # - ./pg/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro

  redisdb:
    image: redis:6.2.4-alpine
    ports:
      - 6379
    env_file: .env
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro

  sidekiq:
    <<: *common
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    depends_on:
      - redisdb
      - app

  app:
    <<: *common
    depends_on:
      - pg
      - redisdb
    ports:
      - 4000:3000
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    tmpfs:
      - /tmp

volumes:
  redis_data: {}
  pg_data: {}
