apiVersion: v1
kind: Service
metadata:
  name: rails-svc
spec:
  type: NodePort
  selector:
    app: rails
  ports:
    - protocol: TCP
      # port exposed by the container
      port: 80
      # the port the app is listening on targetPort
      targetPort: 8080
      name: http
# listens on the default port 8080 and forwards the requests on port 3000 of the pods that have the label rails-app.

# kuberctl apply -f ./config/kube/load_balancer.yml
# <=>
# kubectl expose rc rails-app --port=8080 --target-port=3000 --name=k8-rails-sdkq-lb --type=LoadBalancer
