apiVersion: apps/v1
kind: Deployment
metadata:
  name: cable-dep
  labels: # must match the service
    app: cable
spec:
  replicas: 1
  selector:
    matchLabels: # which pods are we deploying
      app: cable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels: # must match service and replicaset matchlabel
        app: cable
    spec:
      containers:
        - name: cable
          image: ndrean/rails-sc
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
          command: ["bundle"]
          args: ["exec", "puma", "-p", "28080", "./cable/config.ru"]
          ports:
            - containerPort: 28080
          envFrom:
            - configMapRef:
                name: env
---
apiVersion: v1
kind: Service
metadata:
  name: cable-svc
  labels:
    app: cable
spec:
  selector:
    app: cable
  type: ClusterIP # default type
  ports:
    - protocol: TCP
      # port exposed by the service
      port: 28080
      # the port the app is listening on targetPort
      targetPort: 28080
      name: http
