apiVersion: v1
kind: ConfigMap
metadata:
  name: env
data:
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "false"
  # REDIS_SIDEKIQ: redis://redis.default.svc.cluster.local:6379
  # POSTGRES_PASSWORD: fhSBQrF3Dzl9WWA1FfRIjQmU7u3pBtTd
  # REDIS_SIDEKIQ: "redis://user:tq4hBlYvIvq0uU7hYMOYS6ErQKsSA2N8@redis-13424.c258.us-east-1-4.ec2.cloud.redislabs.com:13424/0"
