apiVersion: v1
kind: Service
metadata:
  name: rails-sd-svc
  labels:
    app: rails
spec:
  type: NodePort
  selector:
    app: rails
  ports:
    - protocol: TCP
      # port exposed by the container
      port: 80
      # the port the app is listening on targetPort
      targetPort: 9000
      name: http
