apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq # change from Rails
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sidekiq # change from Rails
    spec:
      containers:
        - name: sidekiq
          image: ndrean/rails-sc
          command: ["bundle"]
          args: ["exec", "sidekiq", "-C", "./config/sidekiq.yml"]
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: env
          ports:
            - name: sidekiqalive
              containerPort: 7433
          livenessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 7433
            initialDelaySeconds: 30 # app specific. Time your sidekiq takes to start processing.
