development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE", "redis://localhost:6379/3" ) %>
  channel_prefix: cable_dev

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE", "redis://localhost:6379/3" ) %>
  channel_prefix: cable_prod
