development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE", "redis://redis:6379/3" ) %>
  channel_prefix: cable_dev

production:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
  channel_prefix: cable_prod
