development:
  adapter: redis
  url: redis://localhost:6379/3
  # <% ENV.fetch("REDIS_CABLE", "redis://localhost:6379/3" ) %>
  channel_prefix: cable_dev

production:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
  channel_prefix: cable_prod
