default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  # primary:
  <<: *default
  database: ortkcbqt
  url: <%= ENV.fetch('POSTGRES_URL','') %>
  #   migrations_path: db/migrate
  # replica:
  #   <<: *default
  #   database: ortkcbqt
  #   url: <%= ENV.fetch('REPLICA_URL','') %>
  #   replica: true

production:
  <<: *default
  database: k8_prod
  username: k8
  password: <%= ENV['K8_DATABASE_PASSWORD'] %>
