default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['POSTGRES_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: k8_dev

production:
  <<: *default
  database: k8_prod
  username: k8
  password: <%= ENV['K8_DATABASE_PASSWORD'] %>
