default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: k8_development
  url: <%= ENV['POSTGRES_URL'] %>
# production:
#   <<: *default
#   database: k8_production
#   password: <%= ENV['K8_DATABASE_PASSWORD'] %>
