default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('POSTGRES_URL', 'postgresql://postgres@localhost:5432') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: k8_development

production:
  <<: *default
  database: k8_production
  username: k8
  password: <%= ENV.fetch('K8_DATABASE_PASSWORD','none') %>
