default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  # primary:
  <<: *default
  database: ortkcbqt
  url: <%= ENV.fetch('POSTGRES_URL','') %>
  #   migrations_path: db/migrate
  # replica:
  #   <<: *default
  #   database: ortkcbqt
  #   url: <%= ENV.fetch('REPLICA_URL','') %>
  #   replica: true
production:
  #   # primary:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
#   database: ortkcbqt
#   url: postgresql://postgres@localhost:5432/ortkcbqt
