production:
  # host: <%= ENV.fetch('REDISLABS_HOST',"") %>
  # password: <%= ENV.fetch('REDISLABS_PWD','') %>
  # port: <%= ENV.fetch('REDISLABS_PORT','') %>
  url: <%= ENV.fetch('REDIS_URL','') %>
  db: 0
