default: &default
  password: secretpwd #<- removed for heroku

development: &dev
  <<: *default
  url: <%= ENV.fetch('REDIS_URL','') %>

production:
  <<: *dev
  url: <%= ENV.fetch('REDISTOGO_URL','') %>
