apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-deployment
  labels:
    app: k8-rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-rails
  template:
    metadata:
      labels:
        app: k8-rails
    spec:
      containers:
        - name: k8-rails
          image: ndrean/k8-rails:v0
          command: ["bundle"]
          args: ["exec", "rails", "s", "-b", "0.0.0.0"]
          ports:
            - containerPort: 3000
          env:
            - name: ELEPHANT_URL
              value: "postgres://ortkcbqt:fhSBQrF3Dzl9WWA1FfRIjQmU7u3pBtTd@batyr.db.elephantsql.com/ortkcbqt"
            - name: RAILS_ENV
              value: "production"
            - name: NODE_ENV
              value: "production"
